[MOB-15746] -- Шаблон фрагмента-контейнера
hhru/android-style-guide pull request #13
Opened 2020-12-04 07:18 UTC by PStrelchenko

2020-12-14 21:51 UTC, user32338 requested changes

2020-12-14 21:51 UTC, user32338 commented on tools/geminio/templates/ContainerFragment/root/src/app_package/ui/container/ContainerFragmentVM.kt.ftl
> +        // TODO
может тут просто Timber.log добавить, что бы и вроде не пусто, и вроде ничего страшного, а то он что есть, что его нет... как будто бы и не нужен этот VM а так хоть какая-то польза) лог пишет) + может сделать тогда и настройку типа включить vm или нет, ну и в самом фрагменте тоже самое

2020-12-14 21:51 UTC, user32338 commented on tools/geminio/templates/ContainerFragment/root/src/app_package/ui/container/di/ContainerFragmentModule.kt.ftl
> +    init {
похоже тут потерялся  bind(${containerFragmentVMName}::class.java)

2020-12-15 08:16 UTC, PStrelchenko commented on tools/geminio/templates/ContainerFragment/root/src/app_package/ui/container/ContainerFragmentVM.kt.ftl
> +        // TODO
Ок, давай добавлю - но уже в следующей задачке.

2020-12-15 08:17 UTC, PStrelchenko commented on tools/geminio/templates/ContainerFragment/root/src/app_package/ui/container/di/ContainerFragmentModule.kt.ftl
> +    init {
Ок, давай добавлю - но уже в следующей задачке.

2020-12-15 09:28 UTC, merged