Update xml-style-guide.md
hhru/android-style-guide pull request #4
Opened 2019-10-25 13:51 UTC by georgyR

2019-10-25 16:56 UTC, user32338 requested changes

2019-10-25 16:56 UTC, user32338 commented on docs/xml-style-guide.md
Стиль заголовка пожялуйста

2019-10-25 16:56 UTC, user32338 commented on docs/xml-style-guide.md
> +hide_icon.xml
hide_icon -  не по код сатйлу твоему надо же hide_icon_fade_250ms.xml

2019-10-25 16:56 UTC, user32338 commented on docs/xml-style-guide.md
> +- Имя имеет маску {описание}
мне кажется нужно меню делать так же как фрагменты т.е.
имя <имя фрагмента>_menu или <имя фрагмента>_<что за меню>

2019-10-25 16:56 UTC, user32338 commented on docs/xml-style-guide.md
желательно еще и везде тогда поправить заголовки на уровень ниже

2019-11-01 14:13 UTC, georgyR commented on docs/xml-style-guide.md
> +hide_icon.xml
> свойства: время действия **(опционально)**

2019-11-01 14:17 UTC, georgyR commented on docs/xml-style-guide.md
> +- Имя имеет маску {описание}
окей, тогда сделаем { имя фрагмента (но без надписи fragment) }_{ описание (опционально) }

2019-11-05 08:54 UTC, PStrelchenkoHH commented on docs/xml-style-guide.md
>  - Максимальная длина строки: 100 символов.
Наверное, здесь должно быть 120 - как наше значение в detekt

2019-11-05 09:00 UTC, PStrelchenkoHH commented on docs/xml-style-guide.md
> +- Имя имеет маску {описание}
Допиши это в маску, пжлст. А то так и останется в комментариях

2019-11-05 10:13 UTC, user32338 commented on docs/xml-style-guide.md
> +hide_icon.xml
ок, но у тебя же просто hide_icon а это может быть  как alpha так и еще куча всяких моментов, можно без времени но само действие ведь должно быть
может это блин в нутри transform по X или Y

2019-11-05 10:25 UTC, user32338 approved these changes

2019-11-05 10:27 UTC, PStrelchenko approved these changes

2019-11-05 10:27 UTC, merged